### PR TITLE
Migrate to GH Actions

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/metanorma-build-scripts/issues/23

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 failing on macOS and Windows.

**Comment by CAMOBAP795** [comment]
Two problems here:
1. Some incompatibility issues for Ruby 2.6 on Windows, I noticed if `https://github.com/riboseinc/asciidoctor-bibliography.git` has been removed from Gemfile, it works IDK why, so I propose to remove it from Gemfile because we don't use it

2. Issue on windows
```
C:\Users\IEUser\asciidoctor-rfc>ruby bin/asciidoctor-rfc2 some.adoc 
spec/examples/hoffmanv2.xml.adocTraceback (most recent call last):
        8: from bin/asciidoctor-rfc2:4:in `<main>'
        7: from C:/tools/ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        6: from C:/tools/ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        5: from C:/tools/ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-ietf-1.0.6/lib/asciidoctor/rfc/v2/converter.rb:3:in `<top (required)>'
        3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-ietf-1.0.6/lib/asciidoctor/rfc/v2/converter.rb:3:in `require_relative'
        2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-ietf-1.0.6/lib/asciidoctor/rfc/common/base.rb:10:in `<top (required)>'
        1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-ietf-1.0.6/lib/asciidoctor/rfc/common/base.rb:11:in `<module:Asciidoctor>'C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1616:in `const_missing': uninitialized constant Asciidoctor::Rfc (NameError)
```

**Comment by CAMOBAP795** [comment]
Separate issue reported for failed tests on windows https://github.com/metanorma/asciidoctor-rfc/issues/108

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Pull request merged**
